package com.maxdemarzi.cargo;

public class TheVerse {
    public static final String THE_VERSE =
            new StringBuilder()

                    //The Core
                    .append("CREATE (s1:Star {name:'White Core'})")
                    .append("CREATE (p11:Planet {name:'Londinium'})")
                    .append("CREATE (m111:Moon {name:'Balkerne'})")
                    .append("CREATE (m112:Moon {name:'Colchester'})")
                    .append("CREATE (p12:Planet {name:'Sihnon'})")
                    .append("CREATE (m121:Moon {name:'Airen'})")
                    .append("CREATE (m122:Moon {name:'Xiansheng'})")
                    .append("CREATE (m123:Moon {name:'Xiaojie'})")
                    .append("CREATE (p13:Planet {name:'Ariel'})")
                    .append("CREATE (m131:Moon {name:'Ariopolis'})")
                    .append("CREATE (m132:Moon {name:'Shiva'})")
                    .append("CREATE (m133:Moon {name:'Poseidon'})")
                    .append("CREATE (p14:Planet {name:'Bellerophon'})")
                    .append("CREATE (p15:Planet {name:'Osiris'})")
                    .append("CREATE (p16:Planet {name:'Liann Jiun'})")
                    .append("CREATE (p17:Planet {name:'Bernadette'})")
                    .append("CREATE (m171:Moon {name:'Nautilus'})")
                    .append("CREATE (m172:Moon {name:'Spinrad'})")
                    .append("CREATE (p18:Planet {name:'Persephone'})")

                    .append("CREATE (p11)-[:ORBITS]->(s1)")
                    .append("CREATE (p12)-[:ORBITS]->(s1)")
                    .append("CREATE (p13)-[:ORBITS]->(s1)")
                    .append("CREATE (p14)-[:ORBITS]->(s1)")
                    .append("CREATE (p15)-[:ORBITS]->(s1)")
                    .append("CREATE (p16)-[:ORBITS]->(s1)")
                    .append("CREATE (p17)-[:ORBITS]->(s1)")
                    .append("CREATE (p18)-[:ORBITS]->(s1)")

                    .append("CREATE (m111)-[:ORBITS]->(p11)")
                    .append("CREATE (m112)-[:ORBITS]->(p11)")
                    .append("CREATE (m121)-[:ORBITS]->(p12)")
                    .append("CREATE (m122)-[:ORBITS]->(p12)")
                    .append("CREATE (m123)-[:ORBITS]->(p12)")
                    .append("CREATE (m131)-[:ORBITS]->(p13)")
                    .append("CREATE (m132)-[:ORBITS]->(p13)")
                    .append("CREATE (m133)-[:ORBITS]->(p13)")
                    .append("CREATE (m171)-[:ORBITS]->(p17)")
                    .append("CREATE (m172)-[:ORBITS]->(p17)")


                    // The Border
                    .append("CREATE (s2:Star {name:'Georgia'})")
                    .append("CREATE (p21:Planet {name:'Ezra'})")
                    .append("CREATE (p22:Planet {name:'Boros'})")
                    .append("CREATE (m221:Moon {name:'Ares'})")
                    .append("CREATE (p23:Planet {name:'Kerry'})")
                    .append("CREATE (p24:Planet {name:'Athens'})")
                    .append("CREATE (m241:Moon {name:'Whitefall'})")
                    .append("CREATE (p25:Planet {name:'Regina'})")
                    .append("CREATE (p26:Planet {name:'Hera'})")
                    .append("CREATE (p27:Planet {name:'Shadow'})")

                    .append("CREATE (p21)-[:ORBITS]->(s2)")
                    .append("CREATE (p22)-[:ORBITS]->(s2)")
                    .append("CREATE (p23)-[:ORBITS]->(s2)")
                    .append("CREATE (p24)-[:ORBITS]->(s2)")
                    .append("CREATE (p25)-[:ORBITS]->(s2)")
                    .append("CREATE (p26)-[:ORBITS]->(s2)")
                    .append("CREATE (p27)-[:ORBITS]->(s2)")

                    .append("CREATE (m221)-[:ORBITS]->(p22)")
                    .append("CREATE (m241)-[:ORBITS]->(p24)")

                    // Red Sun
                    .append("CREATE (s3:Star {name:'Red Sun'})")
                    .append("CREATE (p31:Planet {name:'Greenleaf'})")
                    .append("CREATE (m311:Moon {name:'Dyton'})")
                    .append("CREATE (p32:Planet {name:'Harvest'})")
                    .append("CREATE (m322:Moon {name:'Higgins'})")
                    .append("CREATE (p33:Planet {name:'Jiangyin'})")
                    .append("CREATE (m331:Moon {name:'Dangun'})")
                    .append("CREATE (m332:Moon {name:'Rhilidore'})")
                    .append("CREATE (m333:Moon {name:'Tongyi'})")

                    .append("CREATE (p31)-[:ORBITS]->(s3)")
                    .append("CREATE (p32)-[:ORBITS]->(s3)")
                    .append("CREATE (p33)-[:ORBITS]->(s3)")
                    .append("CREATE (m311)-[:ORBITS]->(p31)")
                    .append("CREATE (m322)-[:ORBITS]->(p32)")
                    .append("CREATE (m331)-[:ORBITS]->(p33)")
                    .append("CREATE (m332)-[:ORBITS]->(p33)")
                    .append("CREATE (m333)-[:ORBITS]->(p33)")

                    // The Rim
                    .append("CREATE (s4:Star {name:'Kalidasa'})")
                    .append("CREATE (p41:Planet {name:'Angel'})")
                    .append("CREATE (p42:Planet {name:'Zephyr'})")
                    .append("CREATE (p43:Planet {name:'Aberdeen'})")
                    .append("CREATE (p44:Planet {name:'Beylix'})")
                    .append("CREATE (p45:Planet {name:'Beaumonde'})")
                    .append("CREATE (p46:Planet {name:'Salisbury'})")

                    .append("CREATE (p41)-[:ORBITS]->(s4)")
                    .append("CREATE (p42)-[:ORBITS]->(s4)")
                    .append("CREATE (p43)-[:ORBITS]->(s4)")
                    .append("CREATE (p44)-[:ORBITS]->(s4)")
                    .append("CREATE (p45)-[:ORBITS]->(s4)")
                    .append("CREATE (p46)-[:ORBITS]->(s4)")

                    .append("CREATE (s5:Star {name:'Blue Sun'})")
                    .append("CREATE (p51:Planet {name:'Muir'})")
                    .append("CREATE (p52:Planet {name:'Highgate'})")
                    .append("CREATE (p53:Planet {name:'Deadwood'})")
                    .append("CREATE (m531:Moon {name:'Haven'})")
                    .append("CREATE (p54:Planet {name:'Miranda'})")
                    .append("CREATE (m541:Moon {name:'Caliban'})")

                    .append("CREATE (p51)-[:ORBITS]->(s5)")
                    .append("CREATE (p52)-[:ORBITS]->(s5)")
                    .append("CREATE (p53)-[:ORBITS]->(s5)")
                    .append("CREATE (p54)-[:ORBITS]->(s5)")
                    .append("CREATE (m531)-[:ORBITS]->(p53)")
                    .append("CREATE (m541)-[:ORBITS]->(p54)")

                    // Made up stations
                    .append("CREATE (st1:Station {name:'Adacyne'})")
                    .append("CREATE (st2:Station {name:'Adia'})")
                    .append("CREATE (st3:Station {name:'Adiere'})")
                    .append("CREATE (st4:Station {name:'Adirain'})")
                    .append("CREATE (st5:Station {name:'Adrallezoen'})")
                    .append("CREATE (st6:Station {name:'Adrel'})")
                    .append("CREATE (st7:Station {name:'Adreland'})")
                    .append("CREATE (st8:Station {name:'Aedald'})")
                    .append("CREATE (st9:Station {name:'Aeddin'})")
                    .append("CREATE (st10:Station {name:'Aeditide'})")
                    .append("CREATE (st11:Station {name:'Aldali'})")
                    .append("CREATE (st12:Station {name:'Aldik'})")
                    .append("CREATE (st13:Station {name:'Audesder'})")
                    .append("CREATE (st14:Station {name:'Aufay'})")
                    .append("CREATE (st15:Station {name:'Augnais'})")
                    .append("CREATE (st16:Station {name:'Aulbres'})")
                    .append("CREATE (st17:Station {name:'Aunenen'})")
                    .append("CREATE (st18:Station {name:'Boranai'})")
                    .append("CREATE (st19:Station {name:'Bordan'})")
                    .append("CREATE (st20:Station {name:'Bosboger'})")
                    .append("CREATE (st21:Station {name:'Chaktaren'})")
                    .append("CREATE (st22:Station {name:'Chamemi'})")
                    .append("CREATE (st23:Station {name:'Colelie'})")
                    .append("CREATE (st24:Station {name:'Conoban'})")
                    .append("CREATE (st25:Station {name:'Conomette'})")
                    .append("CREATE (st26:Station {name:'Costolle'})")
                    .append("CREATE (st27:Station {name:'Couster'})")
                    .append("CREATE (st28:Station {name:'Daras'})")
                    .append("CREATE (st29:Station {name:'Dastryns'})")
                    .append("CREATE (st30:Station {name:'Datulen'})")
                    .append("CREATE (st31:Station {name:'Dysa'})")
                    .append("CREATE (st32:Station {name:'Eavesdown'})")
                    .append("CREATE (st33:Station {name:'Egbonbet'})")
                    .append("CREATE (st34:Station {name:'Erindur'})")
                    .append("CREATE (st35:Station {name:'Erkinen'})")
                    .append("CREATE (st36:Station {name:'Eruka'})")
                    .append("CREATE (st37:Station {name:'Ervekam'})")
                    .append("CREATE (st38:Station {name:'Faurent'})")
                    .append("CREATE (st39:Station {name:'Faurulle'})")
                    .append("CREATE (st40:Station {name:'Gicodel'})")
                    .append("CREATE (st41:Station {name:'Gid'})")
                    .append("CREATE (st42:Station {name:'Gidali'})")
                    .append("CREATE (st43:Station {name:'Hageken'})")
                    .append("CREATE (st44:Station {name:'Hagilur'})")
                    .append("CREATE (st45:Station {name:'Hahda'})")
                    .append("CREATE (st46:Station {name:'Hahyil'})")
                    .append("CREATE (st47:Station {name:'Hulm'})")
                    .append("CREATE (st48:Station {name:'Hulmate'})")
                    .append("CREATE (st49:Station {name:'Huna'})")
                    .append("CREATE (st50:Station {name:'Huola'})")
                    .append("CREATE (st51:Station {name:'Ichinumi'})")
                    .append("CREATE (st52:Station {name:'Ichoriya'})")
                    .append("CREATE (st53:Station {name:'Iderion'})")
                    .append("CREATE (st54:Station {name:'Isanamo'})")
                    .append("CREATE (st55:Station {name:'Isaziwa'})")
                    .append("CREATE (st56:Station {name:'Isbrabata'})")
                    .append("CREATE (st57:Station {name:'Isenairos'})")
                    .append("CREATE (st58:Station {name:'Isenan'})")
                    .append("CREATE (st59:Station {name:'Jita'})")
                    .append("CREATE (st60:Station {name:'Juddi'})")
                    .append("CREATE (st61:Station {name:'Judra'})")
                    .append("CREATE (st62:Station {name:'Kerepa'})")
                    .append("CREATE (st63:Station {name:'Keri'})")
                    .append("CREATE (st64:Station {name:'Kerying'})")
                    .append("CREATE (st65:Station {name:'Keseya'})")
                    .append("CREATE (st66:Station {name:'Laddiaha'})")
                    .append("CREATE (st67:Station {name:'Ladistier'})")
                    .append("CREATE (st68:Station {name:'Lahnina'})")
                    .append("CREATE (st69:Station {name:'Lilmad'})")
                    .append("CREATE (st70:Station {name:'Liparer'})")
                    .append("CREATE (st71:Station {name:'Lirerim'})")
                    .append("CREATE (st72:Station {name:'Lirsautton'})")
                    .append("CREATE (st73:Station {name:'Mateber'})")
                    .append("CREATE (st74:Station {name:'Mattere'})")
                    .append("CREATE (st75:Station {name:'Maturat'})")
                    .append("CREATE (st76:Station {name:'Matyas'})")
                    .append("CREATE (st77:Station {name:'Maurasi'})")
                    .append("CREATE (st78:Station {name:'Mollin'})")
                    .append("CREATE (st79:Station {name:'Moniyyuku'})")
                    .append("CREATE (st80:Station {name:'Mora'})")
                    .append("CREATE (st81:Station {name:'Naga'})")
                    .append("CREATE (st82:Station {name:'Nomash'})")
                    .append("CREATE (st83:Station {name:'Nonni'})")
                    .append("CREATE (st84:Station {name:'Noranim'})")
                    .append("CREATE (st85:Station {name:'Oberen'})")
                    .append("CREATE (st86:Station {name:'Oicx'})")
                    .append("CREATE (st87:Station {name:'Otela'})")
                    .append("CREATE (st88:Station {name:'Ouranienen'})")
                    .append("CREATE (st89:Station {name:'Oyonata'})")
                    .append("CREATE (st90:Station {name:'Passari'})")
                    .append("CREATE (st91:Station {name:'Pator'})")
                    .append("CREATE (st92:Station {name:'Patzcha'})")
                    .append("CREATE (st93:Station {name:'Pavanakka'})")
                    .append("CREATE (st94:Station {name:'Romi'})")
                    .append("CREATE (st95:Station {name:'Roniko'})")
                    .append("CREATE (st96:Station {name:'Sari'})")
                    .append("CREATE (st97:Station {name:'Sonama'})")
                    .append("CREATE (st98:Station {name:'Sosan'})")
                    .append("CREATE (st99:Station {name:'Stoure'})")
                    .append("CREATE (st100:Station {name:'Thakala'})")
                    .append("CREATE (st101:Station {name:'Torvi'})")
                    .append("CREATE (st102:Station {name:'Toshabia'})")
                    .append("CREATE (st103:Station {name:'Totkubad'})")
                    .append("CREATE (st104:Station {name:'Tourier'})")
                    .append("CREATE (st105:Station {name:'Tuomuta'})")
                    .append("CREATE (st106:Station {name:'Uadelah'})")
                    .append("CREATE (st107:Station {name:'Uanim'})")
                    .append("CREATE (st108:Station {name:'Uitra'})")
                    .append("CREATE (st109:Station {name:'Uzistoon'})")
                    .append("CREATE (st110:Station {name:'Vasala'})")
                    .append("CREATE (st111:Station {name:'Vuorrassi'})")
                    .append("CREATE (st112:Station {name:'Wirashoda'})")
                    .append("CREATE (st113:Station {name:'Wiskeber'})")
                    .append("CREATE (st114:Station {name:'Zoohen'})")

                    .append("CREATE (st1)-[:LOCATED_AT]->(m531)")
                    .append("CREATE (st2)-[:LOCATED_AT]->(p51)")
                    .append("CREATE (st3)-[:LOCATED_AT]->(p33)")
                    .append("CREATE (st4)-[:LOCATED_AT]->(p44)")
                    .append("CREATE (st5)-[:LOCATED_AT]->(p17)")
                    .append("CREATE (st6)-[:LOCATED_AT]->(p25)")
                    .append("CREATE (st7)-[:LOCATED_AT]->(p41)")
                    .append("CREATE (st8)-[:LOCATED_AT]->(m322)")
                    .append("CREATE (st9)-[:LOCATED_AT]->(m131)")
                    .append("CREATE (st10)-[:LOCATED_AT]->(p31)")
                    .append("CREATE (st11)-[:LOCATED_AT]->(p27)")
                    .append("CREATE (st12)-[:LOCATED_AT]->(p11)")
                    .append("CREATE (st13)-[:LOCATED_AT]->(p15)")
                    .append("CREATE (st14)-[:LOCATED_AT]->(p16)")
                    .append("CREATE (st15)-[:LOCATED_AT]->(p16)")
                    .append("CREATE (st16)-[:LOCATED_AT]->(p17)")
                    .append("CREATE (st17)-[:LOCATED_AT]->(p27)")
                    .append("CREATE (st18)-[:LOCATED_AT]->(m331)")
                    .append("CREATE (st19)-[:LOCATED_AT]->(p27)")
                    .append("CREATE (st20)-[:LOCATED_AT]->(p51)")
                    .append("CREATE (st21)-[:LOCATED_AT]->(m171)")
                    .append("CREATE (st22)-[:LOCATED_AT]->(m332)")
                    .append("CREATE (st23)-[:LOCATED_AT]->(p13)")
                    .append("CREATE (st24)-[:LOCATED_AT]->(m111)")
                    .append("CREATE (st25)-[:LOCATED_AT]->(p33)")
                    .append("CREATE (st26)-[:LOCATED_AT]->(p17)")
                    .append("CREATE (st27)-[:LOCATED_AT]->(m132)")
                    .append("CREATE (st28)-[:LOCATED_AT]->(m332)")
                    .append("CREATE (st29)-[:LOCATED_AT]->(p24)")
                    .append("CREATE (st30)-[:LOCATED_AT]->(m241)")
                    .append("CREATE (st31)-[:LOCATED_AT]->(m331)")
                    .append("CREATE (st32)-[:LOCATED_AT]->(p18)")
                    .append("CREATE (st33)-[:LOCATED_AT]->(m123)")
                    .append("CREATE (st34)-[:LOCATED_AT]->(m221)")
                    .append("CREATE (st35)-[:LOCATED_AT]->(m112)")
                    .append("CREATE (st36)-[:LOCATED_AT]->(m122)")
                    .append("CREATE (st37)-[:LOCATED_AT]->(p31)")
                    .append("CREATE (st38)-[:LOCATED_AT]->(p14)")
                    .append("CREATE (st39)-[:LOCATED_AT]->(m133)")
                    .append("CREATE (st40)-[:LOCATED_AT]->(p18)")
                    .append("CREATE (st41)-[:LOCATED_AT]->(p15)")
                    .append("CREATE (st42)-[:LOCATED_AT]->(p31)")
                    .append("CREATE (st43)-[:LOCATED_AT]->(m132)")
                    .append("CREATE (st44)-[:LOCATED_AT]->(p41)")
                    .append("CREATE (st45)-[:LOCATED_AT]->(m122)")
                    .append("CREATE (st46)-[:LOCATED_AT]->(m121)")
                    .append("CREATE (st47)-[:LOCATED_AT]->(p46)")
                    .append("CREATE (st48)-[:LOCATED_AT]->(m171)")
                    .append("CREATE (st49)-[:LOCATED_AT]->(p46)")
                    .append("CREATE (st50)-[:LOCATED_AT]->(p46)")
                    .append("CREATE (st51)-[:LOCATED_AT]->(m541)")
                    .append("CREATE (st52)-[:LOCATED_AT]->(m331)")
                    .append("CREATE (st53)-[:LOCATED_AT]->(p44)")
                    .append("CREATE (st54)-[:LOCATED_AT]->(m123)")
                    .append("CREATE (st55)-[:LOCATED_AT]->(p43)")
                    .append("CREATE (st56)-[:LOCATED_AT]->(m132)")
                    .append("CREATE (st57)-[:LOCATED_AT]->(m132)")
                    .append("CREATE (st58)-[:LOCATED_AT]->(p53)")
                    .append("CREATE (st59)-[:LOCATED_AT]->(m332)")
                    .append("CREATE (st60)-[:LOCATED_AT]->(m122)")
                    .append("CREATE (st61)-[:LOCATED_AT]->(m133)")
                    .append("CREATE (st62)-[:LOCATED_AT]->(m123)")
                    .append("CREATE (st63)-[:LOCATED_AT]->(p18)")
                    .append("CREATE (st64)-[:LOCATED_AT]->(p46)")
                    .append("CREATE (st65)-[:LOCATED_AT]->(p33)")
                    .append("CREATE (st66)-[:LOCATED_AT]->(m132)")
                    .append("CREATE (st67)-[:LOCATED_AT]->(m131)")
                    .append("CREATE (st68)-[:LOCATED_AT]->(m541)")
                    .append("CREATE (st69)-[:LOCATED_AT]->(m172)")
                    .append("CREATE (st70)-[:LOCATED_AT]->(m112)")
                    .append("CREATE (st71)-[:LOCATED_AT]->(p12)")
                    .append("CREATE (st72)-[:LOCATED_AT]->(p43)")
                    .append("CREATE (st73)-[:LOCATED_AT]->(p27)")
                    .append("CREATE (st74)-[:LOCATED_AT]->(m541)")
                    .append("CREATE (st75)-[:LOCATED_AT]->(p46)")
                    .append("CREATE (st76)-[:LOCATED_AT]->(p41)")
                    .append("CREATE (st77)-[:LOCATED_AT]->(p33)")
                    .append("CREATE (st78)-[:LOCATED_AT]->(p15)")
                    .append("CREATE (st79)-[:LOCATED_AT]->(p42)")
                    .append("CREATE (st80)-[:LOCATED_AT]->(m322)")
                    .append("CREATE (st81)-[:LOCATED_AT]->(p52)")
                    .append("CREATE (st82)-[:LOCATED_AT]->(m531)")
                    .append("CREATE (st83)-[:LOCATED_AT]->(m123)")
                    .append("CREATE (st84)-[:LOCATED_AT]->(m531)")
                    .append("CREATE (st85)-[:LOCATED_AT]->(p41)")
                    .append("CREATE (st86)-[:LOCATED_AT]->(p52)")
                    .append("CREATE (st87)-[:LOCATED_AT]->(m171)")
                    .append("CREATE (st88)-[:LOCATED_AT]->(p16)")
                    .append("CREATE (st89)-[:LOCATED_AT]->(p32)")
                    .append("CREATE (st90)-[:LOCATED_AT]->(p22)")
                    .append("CREATE (st91)-[:LOCATED_AT]->(p46)")
                    .append("CREATE (st92)-[:LOCATED_AT]->(m311)")
                    .append("CREATE (st93)-[:LOCATED_AT]->(p31)")
                    .append("CREATE (st94)-[:LOCATED_AT]->(m131)")
                    .append("CREATE (st95)-[:LOCATED_AT]->(m221)")
                    .append("CREATE (st96)-[:LOCATED_AT]->(m172)")
                    .append("CREATE (st97)-[:LOCATED_AT]->(p24)")
                    .append("CREATE (st98)-[:LOCATED_AT]->(p27)")
                    .append("CREATE (st99)-[:LOCATED_AT]->(p42)")
                    .append("CREATE (st100)-[:LOCATED_AT]->(p21)")
                    .append("CREATE (st101)-[:LOCATED_AT]->(p12)")
                    .append("CREATE (st102)-[:LOCATED_AT]->(m541)")
                    .append("CREATE (st103)-[:LOCATED_AT]->(p45)")
                    .append("CREATE (st104)-[:LOCATED_AT]->(p53)")
                    .append("CREATE (st105)-[:LOCATED_AT]->(p32)")
                    .append("CREATE (st106)-[:LOCATED_AT]->(m112)")
                    .append("CREATE (st107)-[:LOCATED_AT]->(p18)")
                    .append("CREATE (st108)-[:LOCATED_AT]->(m133)")
                    .append("CREATE (st109)-[:LOCATED_AT]->(m131)")
                    .append("CREATE (st110)-[:LOCATED_AT]->(m541)")
                    .append("CREATE (st111)-[:LOCATED_AT]->(m131)")
                    .append("CREATE (st112)-[:LOCATED_AT]->(m333)")
                    .append("CREATE (st113)-[:LOCATED_AT]->(p45)")
                    .append("CREATE (st114)-[:LOCATED_AT]->(m112)")
                    .toString();

        public static final String TEST_DATA =
                new StringBuilder()
                        // Londinium to Sihnon
                        .append("")
                        .append("CREATE (d1:Docking {code:'d1', departure_date:'11/06/2215 12:00 PM', departure:7758158400, arrival_date:'11/05/2215 12:00 PM', arrival:7758072000})")
                        .append("CREATE (d2:Docking {code:'d2', departure_date:'11/08/2215 12:00 PM', departure:7758331200, arrival_date:'11/07/2215 12:00 PM', arrival:7758244800})")
                        .append("MERGE (st12:Station {name:'Aldik'})")
                        .append("MERGE (st12)-[:HAS_DOCKING]->(d1)")
                        .append("MERGE (st71:Station {name:'Lirerim'})")
                        .append("MERGE (st71)-[:HAS_DOCKING]->(d2)")
                        .append("CREATE (d1)-[:CONNECTED_TO {transit_time:86400}]->(d2)")
                        .toString();
}
